main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('project/', views.Projects.as_view(), name='projects'),
    path('edit_project/<str:project_name>/', views.EditProject.as_view(), name='edit_project'),
    path('project/<str:project_name>/', views.project, name='project'),
    path(
        'project/<str:project_name>/task/<int:task_id>/',
        views.task,
        name='task'
    ),
    path(
        'project/<str:project_name>/task/<int:task_id>/edit_task/',
        views.edit_task,
        name='edit_task'
    ),
    path(
        'project/<str:project_name>/task/<int:task_id>/time_loging/',
        views.time_loging,
        name='time_loging'
    ),
    path(
        'project/<str:project_name>/task/<int:task_id>/log_edit/<int:log_id>/',
        views.LogEdit.as_view(),
        name='log_edit'
    ),
]

tracker/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

from main.views import ChangeLanguageView, Index

urlpatterns = [
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),
    path('', Index.as_view(), name='index'),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField


class Project(models.Model):
    title = models.CharField(max_length=200)
    description = HTMLField()
    unique_name = models.SlugField(max_length=100, unique=True)
    group_executors = models.OneToOneField(Group, on_delete=models.SET)

    class Meta:
        ordering = ['id']
        permissions = (
            ('work_on_project', 'Work on the project'),
        )

    def __str__(self):
        return self.title


class TaskType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class TaskPriority(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Task(models.Model):
    topic = models.CharField(max_length=200)
    description = models.TextField()
    start_date = models.DateField()
    finish_date = models.DateField()
    type = models.ForeignKey(TaskType, on_delete=models.PROTECT)
    priority = models.ForeignKey(TaskPriority, on_delete=models.PROTECT)
    estimated_time = models.IntegerField()
    executor = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, related_name="executor"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, editable=False, related_name="creator"
    )
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="tasks"
    )

    def __str__(self):
        return self.topic

    class Meta:
        ordering = ['id']


class TimeLoging(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    time_spent = models.IntegerField()
    comment = models.CharField(max_length=500)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="time_loging")

    class Meta:
        ordering = ['id']


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=600)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="comments")
    created = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        ordering = ['id']

main/forms.py
import datetime

from django import forms
from django.forms import ValidationError
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from tinymce.widgets import TinyMCE

from .models import Project, TaskType, TaskPriority

TASK_TYPE_CHOICES = [
    (type.id, type.name) for type in TaskType.objects.all()
]

TASK_PRIORITY_CHOICES = [
    (priority.id, priority.name) for priority in TaskPriority.objects.all()
]

ALL_USERS_CHOICES = [
    (user.id, user.username) for user in User.objects.exclude(username="AnonymousUser").filter(is_superuser=False)
]


class ProjectForm(forms.Form):
    title = forms.CharField(max_length=200, label=_('Title'))
    description = forms.CharField(label=_('Description'), widget=TinyMCE)
    unique_name = forms.CharField(max_length=100, label=_('Unique name (for url)'))
    workers = forms.MultipleChoiceField(
        label=_('Workers on the project'),
        widget=forms.CheckboxSelectMultiple,
        choices=ALL_USERS_CHOICES
    )

    def clean_project_name(self):
        unique_name = self.cleaned_data['project_name']

        project = Project.objects.filter(unique_name__iexact=unique_name).exists()
        if project:
            raise ValidationError(_('You can not use this project name.'))

        return unique_name


class ChangeProjectForm(forms.Form):
    title = forms.CharField(max_length=200, label=_('Title'))
    description = forms.CharField(label=_('Description'), widget=TinyMCE)
    workers = forms.MultipleChoiceField(
        label=_('Workers on the project'),
        widget=forms.CheckboxSelectMultiple,
        choices=ALL_USERS_CHOICES
    )


class TaskForm(forms.Form):
    topic = forms.CharField(max_length=200, min_length=1, label=_('Topic'))
    description = forms.CharField(label=_('Description'), widget=forms.Textarea)
    start_date = forms.DateField(label=_('Start date'), initial=datetime.date.today, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    finish_date = forms.DateField(label=_('Finish date'), initial=datetime.date.today, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    type = forms.ChoiceField(label=_('Type'), widget=forms.Select, choices=TASK_TYPE_CHOICES)
    priority = forms.ChoiceField(label=_('Priority'), widget=forms.Select, choices=TASK_PRIORITY_CHOICES)
    estimated_time = forms.IntegerField(label=_('Estimated time'))
    executor = forms.ChoiceField(label=_('Executor'), widget=forms.Select)

    def __init__(self, *args, **kwargs):
        project_name = kwargs.pop('project_name')
        project = Project.objects.get(unique_name=project_name)
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['executor'].choices = [(user.id, user.username) for user in User.objects.filter(groups__name=project.group_executors.name)]


class CommentForm(forms.Form):
    text = forms.CharField(max_length=600, label=_('Text comment'), widget=forms.Textarea)


class TimeLogingForm(forms.Form):
    comment = forms.CharField(max_length=500, label=_('Log comment'), widget=forms.Textarea)
    time_spent = forms.IntegerField(label=_("Time spent (hours)"))


class TestForm(forms.Form):
    # workers = forms.MultipleChoiceField(
    #     label=_('Workers on the project'),
    #     widget=forms.CheckboxSelectMultiple,
    #     choices=ALL_USERS_CHOICES
    # )
    image = forms.ImageField(label=_('Avatar'))

main/views.py
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.forms import fields
from guardian.decorators import permission_required_or_403
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, View, ListView
from django.views.generic.edit import FormView
from django.utils.translation import gettext_lazy as _
from guardian.shortcuts import assign_perm

from accounts.utils import send_change_notification
from .models import Project, TaskType, TaskPriority, Task, Comment, TimeLoging
from .forms import ProjectForm, ChangeProjectForm, TaskForm, CommentForm, TimeLogingForm, TestForm


def check_user_group(user):
    return user.is_superuser or user 


class AdminOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('main:index')

        return super().dispatch(request, *args, **kwargs)


class Index(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        current_user = request.user
        if current_user.is_superuser:
            return redirect('main:projects')

        elif current_user.employee.project:
            return redirect('main:project', project_name=current_user.employee.project.unique_name)
        
        else:
            messages.warning(
                request, _('You do not have access to any projects. Wait for the administrator to add you to any-one.'))
            return redirect('accounts:profile')


class Projects(AdminOnlyView, FormView, ListView):
    model = Project
    form_class = ProjectForm
    paginate_by = 1
    template_name = 'main/projects.html'

    def form_valid(self, form):
        request = self.request
        unique_name_arg = form.cleaned_data['unique_name']

        # check on unique
        if Project.objects.filter(
            unique_name = unique_name_arg
        ).exists():
            messages.warning(request, _("Don't unique url name!"))


        else:
            # create group for user, how will worked on this project
            group_executors = Group.objects.create(name=unique_name_arg)

            new_project = Project()
            new_project.title = form.cleaned_data['title']
            new_project.description = form.cleaned_data['description']
            new_project.unique_name = unique_name_arg
            new_project.group_executors = group_executors
            new_project.save()

            # add workers to group
            for user_id in form.cleaned_data['workers']:
                executor = User.objects.get(pk=user_id)
                group_executors.user_set.add(executor)
                # set user project foreign key
                executor.employee.project = new_project

            # assign permissions for group executors
            assign_perm('work_on_project', group_executors, new_project)

            messages.success(request, _('You are successfully add new project!'))

        return HttpResponseRedirect(request.path_info)


class EditProject(AdminOnlyView, FormView):
    template_name = 'main/edit_project.html'
    form_class = ChangeProjectForm

    def get_initial(self):
        project = Project.objects.get(
            unique_name=self.kwargs["project_name"]
        )
        initial = super().get_initial()
        initial['title'] = project.title
        initial['description'] = project.description
        initial['workers'] = [executor.id for executor in User.objects.filter(groups__name=project.group_executors.name)]
        return initial

    def form_valid(self, form):
        request = self.request
        project = Project.objects.get(
            unique_name=self.kwargs["project_name"]
        )

        project.title = form.cleaned_data['title']
        project.description = form.cleaned_data['description']
        project.save()

        # change group_executors
        group_executors = project.group_executors 
        workers = form.cleaned_data['workers']
        all_users = [user for user in User.objects.exclude(username="AnonymousUser").filter(is_superuser=False)]
        for user in all_users:
            if str(user.id) in workers:
                group_executors.user_set.add(user)
                # change user project foreign key
                user.employee.project = project
            else:
                group_executors.user_set.remove(user)
                # delete user project foreign key
                if user.employee.project == project:
                    user.employee.project = None
            
            user.employee.save()

        messages.success(request, _('You are successfully edit this project!'))

        return redirect('main:projects')


@login_required
@permission_required_or_403('main.work_on_project', (Project, 'unique_name', 'project_name'))
def project(request, project_name):
    current_user = request.user
    project = Project.objects.get(unique_name=project_name)
    tasks = project.tasks.all()
    paginate_by = 1
    dict_for_template = {
        "project": project,
        "query": tasks,
    }
    template_name = 'main/project.html'

    form = TaskForm(request.POST, project_name=project_name)
    if request.method == 'POST' and current_user.is_superuser:
        if form.is_valid():
            new_task = Task()
            new_task.topic = form.cleaned_data['topic']
            new_task.description = form.cleaned_data['description']
            new_task.start_date = form.cleaned_data['start_date']
            new_task.finish_date = form.cleaned_data['finish_date']
            new_task.type = TaskType.objects.get(
                pk=int(form.cleaned_data['type'])
            )
            new_task.priority = TaskPriority.objects.get(
                pk=int(form.cleaned_data['priority'])
            )
            new_task.estimated_time = form.cleaned_data['estimated_time']
            new_task.executor = User.objects.get(
                pk=int(form.cleaned_data['executor'])
            )
            new_task.author = current_user
            new_task.project = project
            new_task.save()

            messages.success(request, _('You are successfully add new task!'))

            return HttpResponseRedirect(request.path_info)

    paginator = Paginator(tasks, paginate_by)

    page_number = request.GET.get('page')
    dict_for_template["page_obj"] = paginator.get_page(page_number)

    if current_user.is_superuser:
        dict_for_template["form"] = TaskForm(project_name=project_name)

    return render(request, template_name, dict_for_template)


@login_required
@permission_required_or_403('main.work_on_project', (Project, 'unique_name', 'project_name'))
def task(request, project_name, task_id):
    current_user = request.user
    current_task = Task.objects.get(pk=task_id)
    comments = current_task.comments.order_by('created').all()
    paginate_by = 1
    dict_for_template = {
        "project_name": project_name,
        "task": current_task,
    }
    template_name = 'main/task.html'

    dict_for_template["spend_time"] = current_task.time_loging.aggregate(Sum('time_spent'))['time_spent__sum'] or 0

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = Comment()
            new_comment.author = current_user
            new_comment.comment = form.cleaned_data['text']
            new_comment.task = current_task
            new_comment.save()

            messages.success(request, _('You are successfully add new comment!'))

            return HttpResponseRedirect(request.path_info)

    paginator = Paginator(comments, paginate_by)

    page_number = request.GET.get('page')
    dict_for_template["page_obj"] = paginator.get_page(page_number)

    dict_for_template["form"] = CommentForm()

    return render(request, template_name, dict_for_template)


def add_to_list_change(list_change, name_field, field, new_value):
    change_text = "Field: {name_field}. Old value: {old_value}; new value: {new_value}."

    if field != new_value:
        list_change.append(
            change_text.format(
                name_field = name_field,
                old_value = field,
                new_value = new_value
            )
        )
        field = new_value

    return list_change, field


@login_required
@permission_required_or_403('main.work_on_project', (Project, 'unique_name', 'project_name'))
def edit_task(request, project_name, task_id):
    current_user = request.user
    current_task = Task.objects.get(pk=task_id)
    dict_for_template = {
        "project_name": project_name,
        "task": current_task,
    }
    template_name = 'main/edit_task.html'

    if request.method == 'POST':
        form = TaskForm(request.POST, project_name=project_name)
        if form.is_valid():
            list_change = []

            list_change, current_task.topic = add_to_list_change(
                list_change,
                "topic",
                current_task.topic,
                form.cleaned_data['topic'],
            )

            list_change, current_task.description = add_to_list_change(
                list_change,
                "description",
                current_task.description,
                form.cleaned_data['description'],
            )

            list_change, current_task.start_date = add_to_list_change(
                list_change,
                "start_date",
                current_task.start_date,
                form.cleaned_data['start_date'],
            )

            list_change, current_task.finish_date = add_to_list_change(
                list_change,
                "finish_date",
                current_task.finish_date,

main/templates/main/_paginations.html
<div class="row">
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                {% if query %}
                    <a href="?q={{ query }}&page=1">&laquo; first</a>
                    <a href="?q={{ query }}&page={{ page_obj.previous_page_number }}">previous</a>
                {% else %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                {% if query %}
                    <a href="?q={{ query }}&page={{ page_obj.next_page_number }}">next</a>
                    <a href="?q={{ query }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% else %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            {% endif %}
        </span>
    </div>
</div>

main/templates/main/edit_log.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

<div class="jumbotron-fluid text-center">
    <div class="container">
        <h1>{% trans 'Time loging edit' %}</h1>
    </div>
</div>

<form method="post">

    {% csrf_token %}
    {% bootstrap_form form %}

    <button class="btn btn-primary">{% trans 'Edit' %}</button>

</form>
{% endblock %}

main/templates/main/edit_project.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block head %}
{{ form.media }}
{% endblock %}

{% block content %}

    <h4>{% trans 'Edit project' %}</h4>
    
    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}
    
        <button class="btn btn-primary">{% trans 'Edit' %}</button>
    
    </form>

{% endblock %}

main/templates/main/edit_task.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block content %}

<div class="jumbotron-fluid text-center">
    <div class="container">
        <h1>{% trans 'Edit task' %} 
            <a class="text-body" href="{% url 'main:task' project_name=project_name task_id=task.id %}">{{ task.topic }}</a>
        </h1>
        <p>
            <a class="text-secondary" href="{% url 'main:time_loging' project_name=project_name task_id=task.id %}">
                {% trans 'Journal logs' %}  
                <img src="{% static 'journal.jpeg' %}" alt="journal logs" width="20" height="20">
            </a>
        </p>
    </div>
</div>

<form method="post">

    {% csrf_token %}
    {% bootstrap_form form %}

    <button class="btn btn-primary">{% trans 'Edit' %}</button>

</form>

{% endblock %}

main/templates/main/project.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block head %}
{{ form.media }}
{% endblock %}

{% block content %}

    <div class="jumbotron-fluid text-center">
        <div class="container">
            <h1>{% trans 'Project' %} {{ project.title }}
                <a href="{% url 'main:edit_project' project_name=project.unique_name %}">
                    <img src="{% static 'edit.png' %}" alt="journal logs" width="25" height="25">
                </a>
            </h1>
        </div>
    </div>

{% if user.is_superuser %}
    <br>
    <div class="jumbotron-fluid text-center">
        <div class="container">
            <h5>{% trans 'Create task' %}</h5>
        </div>
    </div>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Create' %}</button>

    </form>
{% endif %}

<hr>

<div class="jumbotron-fluid text-center">
    <div class="container">
        <h3>{% trans 'Tasks' %}</h1>
    </div>
</div>

<hr>

<div class="container">
    {% for task in page_obj %}
        <div class="edit-pic">
            <a href="{% url 'main:edit_task' project_name=project.unique_name task_id=task.id %}">
                <img src="{% static 'edit.png' %}" alt="journal logs" width="15" height="15">
            </a>
        </div>
        <h4>
            <a class="text-body" href="{% url 'main:task' project_name=project.unique_name task_id=task.id %}">{{ task.topic }}</a>
        </h4>
        <p>{{ task.description }}</p>
        <p class="text-secondary">{% trans 'Start date' %}: {{ task.start_date }};&nbsp; {% trans 'Finish date' %}: {{ task.finish_date }}</p>
        <p>Type: {{ task.type }};&nbsp; Priority: {{ task.priority }}</p>
        <p>Estimated time: {{ task.estimated_time }}</p>
        <p>Author: {{ task.author }};&nbsp; Executor: {{ task.executor }};&nbsp; Project: {{ task.project }}</p>
        <hr>
    {% endfor %}
</div>

{% include 'main/_paginations.html' with query=query page_obj=page_obj %}

{% endblock %}

main/templates/main/projects.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block head %}
{{ form.media }}
{% endblock %}

{% block content %}

    
<div class="jumbotron-fluid text-center">
    <div class="container">
        <h1>{% trans 'Projects' %}</h1>
    </div>
</div>

<br>
<div class="jumbotron-fluid text-center">
    <div class="container">
        <h5>{% trans 'Create project' %}</h5>
    </div>
</div>

<form method="post">

    {% csrf_token %}
    {% bootstrap_form form %}

    <button class="btn btn-primary">{% trans 'Create' %}</button>

</form>

<hr>

<div class="container">
    {% for project in page_obj %}
        <div class="edit-pic">
            <a href="{% url 'main:edit_project' project_name=project.unique_name %}">
                <img src="{% static 'edit.png' %}" alt="journal logs" width="15" height="15">
            </a>
        </div>

        <h4>
            <a class="text-body" href="{% url 'main:project' project_name=project.unique_name %}">{{ project.title }}</a>
        </h4>

        <p>{{ project.description|safe }}</p>

        <hr>
    {% endfor %}
</div>

{% include 'main/_paginations.html' with query=query page_obj=page_obj %}

{% endblock %}

main/templates/main/task.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block content %}

<div class="jumbotron-fluid text-center">
    <div class="container">
        <h1>{% trans 'Task' %} {{ task.topic }}
            <a href="{% url 'main:edit_task' project_name=project_name task_id=task.id %}">
                <img src="{% static 'edit.png' %}" alt="journal logs" width="25" height="25">
            </a>
        </h1>
        <p>
            <a class="text-secondary" href="{% url 'main:time_loging' project_name=project_name task_id=task.id %}">
                {% trans 'Journal logs' %}  
                <img src="{% static 'journal.jpeg' %}" alt="journal logs" width="15" height="15">
            </a>
        </p>
        <p class="text-secondary">
            Spend time: {{ spend_time }} hour(s)&nbsp; Estimated time: {{ task.estimated_time }} hour(s)
        </p>
    </div>
</div>

<form method="post">

    {% csrf_token %}
    {% bootstrap_form form %}

    <button class="btn btn-primary">{% trans 'Comment' %}</button>

</form>

<hr>

<div class="jumbotron-fluid text-center">
    <div class="container">
        <h3>{% trans 'Comments' %}</h1>
    </div>
</div>

<hr>

<div class="container">
    {% for comment in page_obj %}
        <div class="comment-content">
            {% if user.employee.avatar %}
                <div class="avatar"><img src="{{MEDIA_URL}}/{{ user.employee.avatar }}" alt="" width="60" height="60"></div>
            {% endif %}
            <div class="comment-date">{{ comment.created }}</div>
            <div class="comment-author">{{ comment.author }}</div>
            <div class="comment-content">
                {{ comment.comment }}
            </div>
        </div>
        <hr>
    {% endfor %}
</div>

{% include 'main/_paginations.html' with query=query page_obj=page_obj %}

{% endblock %}

main/templates/main/time_loging.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block content %}

<div class="jumbotron-fluid text-center">
    <div class="container">
        <h1>{% trans 'Time loging' %} 
            <a class="text-body" href="{% url 'main:task' project_name=project_name task_id=task.id %}">{{ task.topic }} </a>
            {% trans 'task' %}
        </h1>
    </div>
</div>

<form method="post">

    {% csrf_token %}
    {% bootstrap_form form %}

    <button class="btn btn-primary">{% trans 'Create' %}</button>

</form>

<hr>

<div class="jumbotron-fluid text-center">
    <div class="container">
        <h3>{% trans 'Logs' %}</h1>
    </div>
</div>

<hr>

<div class="container">
    {% for log in page_obj %}
        <div class="comment-content">
            {% if user.is_superuser %}
            <div class="edit-pic">
                <a href="{% url 'main:log_edit' project_name=project_name task_id=task.id log_id=log.id %}">
                    <img src="{% static 'edit.png' %}" alt="journal logs" width="15" height="15">
                </a>
            </div>
            {% endif %}
            {% if user.employee.avatar %}
                <div class="avatar"><img src="{{MEDIA_URL}}/{{ user.employee.avatar }}" alt="" width="60" height="60"></div>
            {% endif %}
            <div class="comment-author">{{ log.author }}</div>
            <div class="comment-time-spent">Spent {{ log.time_spent }} hour(s)</div>
            <div class="comment-content">
                {{ log.comment }}
            </div>
        </div>
        <hr>
    {% endfor %}
</div>

{% include 'main/_paginations.html' with query=query page_obj=page_obj %}

{% endblock %}